<?php

require_once 'lib/lib.xml-rpc.php';
require_once 'lib/lib.csv.php';

if (isset($_POST['action'])) {
    set_include_path(realpath(__DIR__) . '/../../lib');
    $getWP = slashes($_POST);
    $excludeMerchant = str_replace(', ', ', !', substr_replace($options['exclude_merchant'], '!', '0', '0'));
    $excludeMerchant = explode(', ', $excludeMerchant);
    $getWP['keywords'] = array_filter(explode("\n", str_replace("\r", "", $getWP['keywords'])));
    $created = date("Y-m-j");
    $pubDate = rssDate();
    $dataItem[] = '';
    $i = '1';
    $countPost = '1';
    $wpXML =  '<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site\'s posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="Prosperent Hunter/' . $version . '" created="' . $created . '" -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
    <title>Wordpress</title> 
    <link>http://wordpress.org</link>
    <description>Just another WordPress site</description>
    <pubDate>' . $pubDate . '</pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url>http://wordpress.org</wp:base_site_url>
    <wp:base_blog_url>http://wordpress.org</wp:base_blog_url>

    <wp:author><wp:author_id>1</wp:author_id><wp:author_login>admin</wp:author_login><wp:author_email>eee@eee.com</wp:author_email><wp:author_display_name><![CDATA[admin]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

    <generator>http://wordpress.org/?v=3.5.1</generator>' . "\n";

    foreach ($getWP['keywords'] as $keyGroups) {
        $keyGroups = explode("|", $keyGroups);
        $keywords = $keyGroups['0'];
        $connectProsperent = connectProsperent($options['primary_api'], $keywords, $getWP['serpLimit'], '', $excludeMerchant, '', '', '', $getWP['tracking'], $options['cache_dir']);
        foreach($connectProsperent['data'] as $item) {
            array_push($dataItem, $item);
            if (empty($keyGroups['1'])) {
                 $dataItem[$i]['wp_category'] = 'Uncategorized';
            } else {
                $dataItem[$i]['wp_category'] = $keyGroups['1'];
            }

            $i++;
        }

        if (isset($connectProsperent['error'])) {
            $_POST['action'] = 'error';
            $alertMsg = 'alert-danger';
            $wpMsg = '<p><span class="label label-danger">Error</span> There is something wrong</p>';
        } else {
            $dataProsperent = array_filter($dataItem);
        }
    }

    foreach($dataProsperent as $getData) {
        $getItem = slashes($getData);
        shuffle($getWP['template']);
        $postDate = randDate(date('Ymd', strtotime('-' . $options['random_date'] . ' day', time())), date('Ymd', time()), 'wpxml');
        $item_catalogId = $getItem['catalogId'];
        $item_productId = $getItem['productId'];
        $item_affiliate_url = $getItem['affiliate_url'];
        $item_image_url = $getItem['image_url'];
        $item_keyword = $getItem['keyword'];
        $item_keywords = $getItem['keywords'];
        $item_celebrity = $getItem['celebrity'];
        $item_description = $getItem['description'];
        $item_category = $getItem['category'];
        $item_price = $getItem['price'];
        $item_price_sale = $getItem['price_sale'];
        $item_currency = $getItem['currency'];
        $item_merchant = $getItem['merchant'];
        $item_brand = $getItem['brand'];
        $item_upc = $getItem['upc'];
        $item_isbn = $getItem['isbn'];
        $item_sales = $getItem['sales'];
        $getProducts[] = '<p><span class="label label-success">Success</span> Product ID: ' . $getItem['productId'] . '</p>';
        $queryTemplate = "SELECT * FROM template WHERE ID = '" . $getWP['template']['0'] . "'";
        $resultTemplate = $mysqli->query($queryTemplate) OR trigger_error($mysqli->error . "[$queryTemplate]");
        if ($resultTemplate->num_rows <= '0') {
            exit('No Template');
        }

        while ($templateRow = $resultTemplate->fetch_array(MYSQLI_ASSOC)) {
            $template_title = $templateRow['title'];
            $template_description = $templateRow['post_template'];
            $template_compareTable = $templateRow['compare_table'];

            // Spin title
            $title = spin($template_title);
            $title = str_replace("##PRODUCTID##", $item_productId, $title);
            $title = str_replace("##URL##", $item_affiliate_url, $title);
            $title = str_replace("##IMAGE##", $item_image_url, $title);
            $title = str_replace("##TITLE##", $item_keyword, $title);
            $title = str_replace("##DESCRIPTION##", $item_description, $title);
            $title = str_replace("##CATEGORY##", $item_category, $title);
            $title = str_replace("##PRICE##", $item_price, $title);
            $title = str_replace("##PRICESALE##", $item_price_sale, $title);
            $title = str_replace("##CURRENCY##", $item_currency, $title);
            $title = str_replace("##MERCHANT##", $item_merchant, $title);
            $title = str_replace("##BRAND##", $item_brand, $title);
            $title = str_replace("##UPC##", $item_upc, $title);
            //$title = str_replace("##SUBFIX##', $subFix, $title);
            //$title = str_replace("##PREFIX##', $preFix, $title);

            // Spin content
            $contents = spin($template_description);
            $contents = str_replace("##PRODUCTID##", $item_productId, $contents);
            $contents = str_replace("##URL##", $item_affiliate_url, $contents);
            $contents = str_replace("##IMAGE##", $item_image_url, $contents);
            $contents = str_replace("##TITLE##", $item_keyword, $contents);
            $contents = str_replace("##DESCRIPTION##", $item_description, $contents);
            $contents = str_replace("##CATEGORY##", $item_category, $contents);
            $contents = str_replace("##PRICE##", $item_price, $contents);
            $contents = str_replace("##PRICESALE##", $item_price_sale, $contents);
            $contents = str_replace("##CURRENCY##", $item_currency, $contents);
            $contents = str_replace("##MERCHANT##", $item_merchant, $contents);
            $contents = str_replace("##BRAND##", $item_brand, $contents);
            $contents = str_replace("##UPC##", $item_upc, $contents);
            /*$contents = str_replace("##COMPARE##', $compareTable, $contents);
            $contents = str_replace("##MERCHANTLOGO##', $merchantLogo, $contents);
            $contents = str_replace("##BRANDLOGO##', $brandLogo, $contents);
            $contents = str_replace("##SUBFIX##', $subFix, $contents);
            $contents = str_replace("##PREFIX##', $preFix, $contents);*/
        }

        $postMeta = spin($getWP['options']);
        $postMeta = str_replace("##PRODUCTID##", $item_productId, $postMeta);
        $postMeta = str_replace("##URL##", $item_affiliate_url, $postMeta);
        $postMeta = str_replace("##IMAGE##", $item_image_url, $postMeta);
        $postMeta = str_replace("##TITLE##", $item_keyword, $postMeta);
        $postMeta = str_replace("##DESCRIPTION##", $item_description, $postMeta);
        $postMeta = str_replace("##CATEGORY##", $item_category, $postMeta);
        $postMeta = str_replace("##PRICE##", $item_price, $postMeta);
        $postMeta = str_replace("##PRICESALE##", $item_price_sale, $postMeta);
        $postMeta = str_replace("##CURRENCY##", $item_currency, $postMeta);
        $postMeta = str_replace("##MERCHANT##", $item_merchant, $postMeta);
        $postMeta = str_replace("##BRAND##", $item_brand, $postMeta);
        $postMeta = str_replace("##UPC##", $item_upc, $postMeta);
        /*$postMeta = str_replace("##COMPARE##', $compareTable, $postMeta);
        $postMeta = str_replace("##MERCHANTLOGO##', $merchantLogo, $postMeta);
        $postMeta = str_replace("##BRANDLOGO##', $brandLogo, $postMeta);
        $postMeta = str_replace("##SUBFIX##', $subFix, $postMeta);
        $postMeta = str_replace("##PREFIX##', $preFix, $postMeta);*/

        $title = htmlentities($title, ENT_NOQUOTES, 'UTF-8');
        $tag = tag($item_keyword);
        $cate = explode(',', $tag);
        $catarr = '';
        foreach ($cate as $wpTag) {
            $bgtag = preg_replace('/[^A-Za-z0-9-]/', ' ', $wpTag);
                if ($wpTag != "") {
                    $tagSlug = slug($wpTag);
                    $catarr .= '
        <category domain="post_tag" nicename="' . $tagSlug . '"><![CDATA[' . $wpTag . ']]></category>';
                }
        }

        $titleSlug = slug($item_keyword);
        $categorySlug = slug($getItem['wp_category']);
        $catarr .= '
        <category domain="category" nicename="' . $categorySlug . '"><![CDATA[' . $getItem['wp_category'] . ']]></category>';
        $wpXML .= '
    <item>
        <title>' . $title . '</title>
        <link>http://wordpress.org/' . $titleSlug . '/</link>     
        <dc:creator><![CDATA[admin]]></dc:creator>
        <guid isPermaLink="false">http://wordpress.org/' . $titleSlug . '/</guid>
        <description></description>
        <content:encoded><![CDATA[' . $contents . ']]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id>' . $countPost . '</wp:post_id>
        <wp:post_date>' . $postDate . '</wp:post_date>
        <wp:post_date_gmt>' . $postDate . '</wp:post_date_gmt>
        <wp:comment_status>closed</wp:comment_status>
        <wp:ping_status>open</wp:ping_status>
        <wp:post_name>' . $titleSlug . '</wp:post_name>
        <wp:status>publish</wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type>post</wp:post_type>
        <wp:post_password></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>' . $catarr;
        if (isset($postMeta)) {
            foreach ($postMeta as $name => $value) {
                $wpXML .= '
        <wp:postmeta>
            <wp:meta_key>' . $name . '</wp:meta_key>
            <wp:meta_value><![CDATA[' . $value . ']]></wp:meta_value>
        </wp:postmeta>';
            }
        }

        $wpXML .= '
    </item>' . "\n";
        $countPost++;
    }

    $wpXML .= '</channel>
</rss>';
    $flieXML = 'module/xml/download/wordpress/' . date("Y-m-d_H-i-s") . '.xml';
    $wpXML = get_magic_quotes_gpc() ? stripslashes($wpXML) : $wpXML;
    $fp = fopen($flieXML, 'w');
    fwrite($fp, $wpXML);
    fclose($fp);
    $alertMsg = 'alert-success';
    $wpMsg = '<p>Create wordpress XML file: <strong><a href="' . $flieXML . '">Download (Right click and save link as)</a></strong></p>';

}

$queryTemplate = "SELECT * FROM template";
$resultTemplate = $mysqli->query($queryTemplate) OR trigger_error($mysqli->error . "[$queryTemplate]");

?>

                            <div class="content-box">
                                <!-- start: CONTENT HEAD -->
                                <div class="content-head">
                                    <h2><i class="fa fa-sitemap color"></i> <?php echo $module['title']; ?></h2>
                                </div>
                                <!-- end: CONTENT HEAD -->
                                <!-- start: CONTENT BODY -->
                                <div class="content-body">
                                    <?php if (isset($_POST['action'])) { ?>
                                    <div class="alert <?php echo $alertMsg; ?>">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                                        <?php if ($_POST['action'] == 'generator') {
                                            echo $wpMsg;
                                            foreach ($getProducts as $products) { ?>
                                                <?php echo $products ?>
                                            <?php }
                                        } ?>
                                    </div>
                                    <?php } ?>
                                    <form name="wordpress-xml" class="form-horizontal" data-toggle="validator" action="" method="POST">
                                        <input type="hidden" name="action" value="generator" />
                                        <h3>Blog Info</h3>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Post Start Date:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="start-post" class="form-control" placeholder="Post start date" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Post End Date:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="end-post" class="form-control" placeholder="Post end date" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <h3>Preferences</h3>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">API:</label>
                                                    <div class="col-md-10">
                                                        <input type="text" name="api" class="form-control" placeholder="API (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">Keywords:</label>
                                                    <div class="col-md-10">
                                                        <textarea name="keywords" class="form-control" rows="2" placeholder="Keywords|Category (One per line)" required></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">Tracking:</label>
                                                    <div class="col-md-10">
                                                        <input type="text" name="tracking" class="form-control" placeholder="Track a site's purchase through (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Product Result:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="serpLimit" class="form-control" placeholder="Total post" required />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Brand:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="brand" class="form-control" placeholder="Filter by brand (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Merchant:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="merchant" class="form-control" placeholder="Filter by merchant (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Category:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="category" class="form-control" placeholder="Filter by categories (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Max Price:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="maxPrice" class="form-control" placeholder="Filter by max price (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label class="col-md-4 control-label">Min Price:</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="minPrice" class="form-control" placeholder="Filter by min price (Optional)" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label">Template:</label>
                                                    <div class="col-md-10">
                                                        <select name="template[]" class="form-control" multiple="multiple" required>
                                                            <?php while ($templateRow = $resultTemplate->fetch_array(MYSQLI_ASSOC)) { ?>
                                                            <option value="<?php echo $templateRow['ID']; ?>"><?php echo $templateRow['name']; ?></option>
                                                            <?php } ?>
                                                        </select>
                                                        <input type="button"t name="select-all" class="form-control btn black" value="Select All" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <h3>Options</h3>
                                        <fieldset id="options">
                                        </fieldset>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label class="col-md-2 control-label"></label>
                                                    <div class="col-md-10">
                                                        <input type="button" class="form-control btn black more-option" value="Add More Options" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12 text-right">
                                                <div class="form-group">
                                                    <button type="submit" class="btn blue" disabled>Submit</button>
                                                    <button type="reset" class="btn red">Reset</button>
                                                    <button type="button" class="btn white" onClick="history.go(-1);return true;">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

